#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "librechat-anarcho"
name = "LibreChat Anarcho"
description.en = "Revolutionary decentralized communication platform for anarcho-syndicalist collectives"
description.fr = "Plateforme de communication décentralisée révolutionnaire pour collectifs anarcho-syndicalistes"

version = "2025.08.22~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://github.com/UNionlibertaireAnarchiste-org"
demo = "https://github.com/UNionlibertaireAnarchiste-org/mirotalk"
admindoc = "https://github.com/UNionlibertaireAnarchiste-org/mirotalk_ynh"
code = "https://github.com/UNionlibertaireAnarchiste-org/mirotalk"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "500M"
ram.build = "500M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/UNionlibertaireAnarchiste-org/mirotalk/archive/master.tar.gz"
    sha256 = "99a601a52dcc2f610a3ae6b313f7ace5fb5740d6b389a4f85cccddea3a4cbbc2"
    autoupdate.upstream = "https://github.com/UNionlibertaireAnarchiste-org/mirotalk/"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
