#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "mirotalk"
name = "MiroTalk"
description.en = "Real-Time Video Conferences Up to 8k and 60fps"
description.fr = "Vidéoconférences en temps réel jusqu'à 8k et 60fps"

version = "2025.07.19~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "AGPL-3.0"
website = "https://meet.no42.org/"
demo = "https://meet.no42.org/"
admindoc = "https://docs.mirotalk.com/"
code = "https://github.com/miroslavpejic85/mirotalk"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "500M"
ram.build = "500M"
ram.runtime = "100M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/miroslavpejic85/mirotalk/archive/4a2e64b45d2ea4fc571f32d17359c5900ab2ddf0.tar.gz"
    sha256 = "566e2bd6c16539987923961662ad7d2fca357a12ac3db62b7028f3a449d6d7c8"
    autoupdate.upstream = "https://github.com/miroslavpejic85/mirotalk/"
    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
